import test from 'node:test';import assert from 'node:assert/strict';
import {publicPayload} from './funding.mjs';
import {fundingMetrics} from '../src/funding.js';
const base=()=>({settings:[{cause_id:'a',publish_ready:true,featured:true,currency:'CAD',funding_goal:100}],causes:[{id:'a',name:'A',status:'approved'}],translations:[],registrations:[{id:'r',user_id:'private-user',cause_id:'a',status:'confirmed'}],contributions:[],allocations:[]});
test('unpublished placeholders, unapproved causes and merged causes stay private',()=>{for(const kind of ['unpublished','unapproved','merged']){const d=base();if(kind==='unpublished')d.settings[0].publish_ready=false;if(kind==='unapproved')d.causes[0].status='pending_approval';if(kind==='merged')d.causes[0].canonical_cause_id='other';assert.equal(publicPayload(d).causes.length,0);}});
test('confirmed allocations supersede legacy contributions and exclude refunds and other currencies',()=>{const d=base();d.contributions=[{registration_id:'r',cause_id:'a',amount:50,currency:'CAD',status:'confirmed'}];d.allocations=[{registration_id:'r',cause_id:'a',cause_amount:25,currency:'CAD',status:'confirmed'}];assert.equal(publicPayload(d).causes[0].raisedAmount,25);d.allocations[0].status='refunded';assert.equal(publicPayload(d).causes[0].raisedAmount,0);d.allocations=[];d.contributions[0].currency='USD';assert.equal(publicPayload(d).causes[0].raisedAmount,0);});
test('legacy contributions require confirmed registrations and are summed in cents',()=>{const d=base();d.contributions=[{registration_id:'r',cause_id:'a',amount:'0.10',currency:'CAD',status:'confirmed'},{registration_id:'r',cause_id:'a',amount:'0.20',currency:'CAD',status:'confirmed'}];assert.equal(publicPayload(d).causes[0].raisedAmount,.3);d.registrations[0].status='refunded';assert.equal(publicPayload(d).causes[0].raisedAmount,0);});
test('public projection localizes names, deduplicates supporters and omits personal records',()=>{const d=base();d.translations=[{cause_id:'a',locale:'fr-CA',name:'Français'}];d.registrations.push({...d.registrations[0],id:'r2'});const p=publicPayload(d);assert.equal(p.causes[0].name,'Français');assert.equal(p.causes[0].supporterCount,1);assert.ok(!JSON.stringify(p).includes('private-user'));assert.ok(!('allocations' in p));});
test('unset goals remain unset; progress handles zero and overfunding',()=>{const d=base();d.settings[0].funding_goal=null;assert.equal(publicPayload(d).causes[0].goalAmount,null);assert.equal(fundingMetrics({goalAmount:null,raisedAmount:0}).percent,null);assert.equal(fundingMetrics({goalAmount:100,raisedAmount:0}).percent,0);const f=fundingMetrics({goalAmount:100,raisedAmount:150});assert.equal(f.percent,150);assert.equal(f.remaining,0);assert.equal(fundingMetrics({raisedAmount:-1}).raised,null);});
